version: "3.9"

services:
  db:
    image: postgres:15
    container_name: accounts-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounts
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 10

  accounts-service:
    build:
      context: ./services/accounts
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/accounts?sslmode=disable

  transactions-service:
    build:
      context: ./services/transactions
    ports:
      - "8081:8081"
    depends_on:
      accounts-service:
        condition: service_started
    environment:
      DB_URL: postgres://postgres:postgres@db:5432/accounts?sslmode=disable

volumes:
  pgdata:
